export const VALIDATE_INPUT = 'VALIDATE_INPUT';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const HANDLE_ERROR = 'HANDLE_ERROR';
export const SET_LOADING_STATUS = 'CHECK_LOADING_STATUS';
